- raw: "apt-get update; apt-get install -y python"

- name: "Copying BashRC"
  template:
    src: ../files/bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: 0644

- name: "Removing Roots BashRC"
  file:
    path: /root/.bashrc
    state: absent

- name: "Removing bashrc in /etc/skel"
  file:
    path: /etc/skel/.bashrc
    state: absent


- name: "Installing figlet"
  apt:
    name: figlet

# The message of the day puts out much data, which doesn't really help, so let's get rid
# of it and replace it with a banner so that the viewers can easily see on what server we are.
#- name: "Disableing the default Message of the day"
#  shell: chmod -R 0644 /etc/update-motd.d/*
- name: "Disableing the default Message of the day"
  file:
    path: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0644
    recurse: yes

- name: "Removing 50-landscape-sysinfo as it is a symlink and chmod 0644 isn't enough"
  file:
    path: /etc/update-motd.d/50-landscape-sysinfo
    state: absent

- name: "Setting the correct rights for the folder itself."
  file:
    path: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755
    
- name: "Copying Banner file over"
  copy:
    src: ../files/systembanner.sh
    dest: /etc/update-motd.d/999-systembanner
    owner: root
    group: root
    mode: 0755

# The default sshd shows the last login of a user inkl. the IP. Again not usefull information
# for the viewers. So I'll remove that by disableing PrintLastLogin in sshd_config
- name: "Copying SSHD config over"
  copy:
    src: ../files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
  - restart-ssh

# With the zoom level I'm using in the videos I sometimes end up with line breaks. To make them
# better readalbe without annoyingly zooming in and out, I've written a small python script that
# highlights the lines.
- name: "Copying highligther Script"
  copy:
    src: ../files/highlighter.py
    dest: /bin/highlighter
    owner: root
    group: root
    mode: 0755

- name: "Copying vimrc"
  copy:
    src: ../files/vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: 0644
