- name: "Installing necessary NFS packages"
  apt:
    name: "{{ item }}"
  with_items:
  - nfs-common
  - iptables-persistent

# rpcbind shouldn't be exposed to the whole internet.
- name: "Setting Firewall Rules, rpcbind, allow the docker servers"
  iptables:
    chain: INPUT
    source: "{{ item }}"
    destination_port: 111
    protocol: tcp
    jump: ACCEPT
  with_items:
  - "{{ hostvars['docker-nfs']['ansible_default_ipv4']['address'] }}"
  notify:
  - iptables-save

- name: "Setting Firewall Rules, rpcbind, reject the rest."
  iptables:
    chain: INPUT
    destination_port: 111
    protocol: tcp
    jump: REJECT
  notify:
  - iptables-save


- name: "Setting IPv6 Firewall Rules, rpcbind, allow the docker servers"
  iptables:
    chain: INPUT
    source: "{{ item }}"
    destination_port: 111
    jump: ACCEPT
    protocol: tcp
    ip_version: ipv6
  with_items:
  - "{{ hostvars['docker-nfs']['ansible_default_ipv6']['address'] }}"
  notify:
  - iptables-save

- name: "Setting IPv6 Firewall Rules, rpcbind, reject the rest."
  iptables:
    chain: INPUT
    destination_port: 111
    jump: REJECT
    protocol: tcp
    ip_version: ipv6
  notify:
  - iptables-save

- name: "Setting Firewall Rules, rpcbind, allow the docker servers"
  iptables:
    chain: INPUT
    source: "{{ item }}"
    destination_port: 111
    protocol: udp
    jump: ACCEPT
  with_items:
  - "{{ hostvars['docker-nfs']['ansible_default_ipv4']['address'] }}"
  notify:
  - iptables-save

- name: "Setting Firewall Rules, rpcbind, reject the rest."
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 111
    jump: REJECT
  notify:
  - iptables-save


- name: "Setting IPv6 Firewall Rules, rpcbind, allow the docker servers"
  iptables:
    chain: INPUT
    source: "{{ item }}"
    destination_port: 111
    protocol: udp
    jump: ACCEPT
    ip_version: ipv6
  with_items:
  - "{{ hostvars['docker-nfs']['ansible_default_ipv6']['address'] }}"
  notify:
  - iptables-save

- name: "Setting IPv6 Firewall Rules, rpcbind, reject the rest."
  iptables:
    chain: INPUT
    destination_port: 111
    jump: REJECT
    protocol: udp
    ip_version: ipv6
  notify:
  - iptables-save
