- name: "Installing necessary packages"
  apt:
    name: "{{ item }}"
  with_items:
  - ca-certificates
  - curl
  - apt-transport-https
  - software-properties-common

- name: "Adding apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Adding apt repository and refreshing apt cache"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: yes

- name: "Installing docker"
  apt:
    name: docker.io
